############################################################################################
##      This is a demo config. Rename the file to config.yaml and add your settings      ##
############################################################################################

port: 9000
mediaPath: "./media"
token: 123456
logconfig:
  level: debug
  file: logfile.log

movies:
  path  : './media/movies'
  api   : 'api.themoviedb.org/3'
  key   : '<api_key>'
  json  : 'movies.json'
music:
  path  : './media/music'
  api   : 'api.spotify.com/v1'
  key   : '<access_token>'
  json  : 'music.json'
tv:
  path  : './media/tv'
  api   : 'api.themoviedb.org/3'
  key   : '<api_key>'
  json  : 'tv.json'
